[SddmGreeterSettings]
# Theonix SDDM Theme Metadata
Background     = assets/background.png
Type           = image
HaveThemeBackgroundColor = false
HaveThemeBackground      = true
ScreenPadding  = 0
Font           = Inter
FontSize       = 10
DpiAwareness   = true
