[build]
  # Set the base directory to where the website files live
  base = "website"
  
  # The command to build the Tailwind CSS
  command = "npm run build:css"
  
  # The directory containing the built HTML/CSS files to deploy
  publish = "."

[[redirects]]
  from = "/docs"
  to = "/documentation.html"
  status = 301
  force = true

[[redirects]]
  from = "/download"
  to = "/download.html"
  status = 301
  force = true
