# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Finished module configuration for Theonix OS.
---
restartNowEnabled: true
restartNowChecked: true

restartNowCommand: "systemctl -i reboot"

notifyOnFinished: false
