# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# GRUB config module configuration for Theonix OS.
---
distributor: "Theonix OS"

keepDistributor: false

cmdlineLinuxDefault: "quiet loglevel=3 systemd.show_status=auto rd.udev.log_level=3 splash"
cmdlineLinux: ""

efiBootloaderId: "theonix"
gsName: "partitions"

timeout: 3
