#!/bin/bash
# =============================================================================
# Theonix OS — Initramfs Generation Script (Host Side)
# =============================================================================
# Runs on the Live ISO (dontChroot: true) to copy the kernel into the target
# system, configure mkinitcpio for a hard drive, and generate the initramfs.
# =============================================================================

set -e

# ${ROOT} is provided by Calamares (the mount point of the installed system)
if [ -z "${ROOT}" ]; then
    echo "ERROR: ROOT variable is not set."
    exit 1
fi

echo "==> initcpio: Copying kernel from Live ISO to Target System..."
mkdir -p "${ROOT}/boot"

# The kernel is mounted on the Live ISO at /run/archiso/bootmnt/theonix/boot/x86_64/vmlinuz-linux
# If that path doesn't exist, fallback to the generic arch path
KERNEL_SRC="/run/archiso/bootmnt/theonix/boot/x86_64/vmlinuz-linux"
if [ ! -f "$KERNEL_SRC" ]; then
    KERNEL_SRC="/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux"
fi

if [ -f "$KERNEL_SRC" ]; then
    cp "$KERNEL_SRC" "${ROOT}/boot/vmlinuz-linux"
else
    echo "WARNING: Could not find kernel on Live ISO to copy!"
fi

echo "==> initcpio: Writing target /etc/mkinitcpio.conf"

ROOT_FS=$(awk '$2=="/" {print $3; exit}' "${ROOT}/etc/fstab" || echo "ext4")
ROOT_FS=${ROOT_FS:-ext4}

HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)

case "$ROOT_FS" in
    btrfs)
        HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block btrfs filesystems fsck)
        ;;
    xfs|f2fs)
        HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)
        ;;
esac

if grep -qE 'cryptdevice|/dev/mapper/' "${ROOT}/etc/fstab" 2>/dev/null || \
   { [ -f "${ROOT}/etc/crypttab" ] && grep -qv '^#' "${ROOT}/etc/crypttab" 2>/dev/null; }; then
    HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block encrypt filesystems fsck)
    case "$ROOT_FS" in
        btrfs) HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block encrypt btrfs filesystems fsck) ;;
    esac
fi

{
    echo "# Generated by Theonix OS installer"
    echo "MODULES=()"
    echo "BINARIES=()"
    echo "FILES=()"
    printf 'HOOKS=('
    printf '%s ' "${HOOKS[@]}"
    echo ')'
} > "${ROOT}/etc/mkinitcpio.conf"

echo "==> initcpio: Removing live-CD remnants from target system..."
rm -f "${ROOT}/etc/mkinitcpio.conf.d/archiso.conf" 2>/dev/null
rm -f "${ROOT}/etc/mkinitcpio.d/linux.preset" 2>/dev/null

echo "==> initcpio: Generating standard linux.preset..."
{
    echo "PRESETS=(\"default\" \"fallback\")"
    echo "default_kver=\"/boot/vmlinuz-linux\""
    echo "default_image=\"/boot/initramfs-linux.img\""
    echo "fallback_kver=\"/boot/vmlinuz-linux\""
    echo "fallback_image=\"/boot/initramfs-linux.img\""
    echo "fallback_options=\"-S autodetect\""
} > "${ROOT}/etc/mkinitcpio.d/linux.preset"

echo "==> initcpio: Running mkinitcpio -P inside target..."
arch-chroot "${ROOT}" mkinitcpio -P

echo "==> initcpio: Complete"
