#!/bin/bash
# =============================================================================
# Theonix OS — Initramfs Generation Script
# =============================================================================
# Replaces the Arch-specific initcpiocfg + initcpio Calamares modules.
# Writes /etc/mkinitcpio.conf and runs mkinitcpio -P inside the target chroot.
# =============================================================================

set -e

echo "==> initcpio: Writing /etc/mkinitcpio.conf"

ROOT_FS=$(awk '$2=="/" {print $3; exit}' /etc/fstab)
ROOT_FS=${ROOT_FS:-ext4}

HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)

case "$ROOT_FS" in
    btrfs)
        HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block btrfs filesystems fsck)
        ;;
    xfs|f2fs)
        HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck)
        ;;
esac

if grep -qE 'cryptdevice|/dev/mapper/' /etc/fstab 2>/dev/null || \
   { [ -f /etc/crypttab ] && grep -qv '^#' /etc/crypttab 2>/dev/null; }; then
    HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block encrypt filesystems fsck)
    case "$ROOT_FS" in
        btrfs) HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block encrypt btrfs filesystems fsck) ;;
    esac
fi

{
    echo "# Generated by Theonix OS installer"
    echo "MODULES=()"
    echo "BINARIES=()"
    echo "FILES=()"
    printf 'HOOKS=('
    printf '%s ' "${HOOKS[@]}"
    echo ')'
} > /etc/mkinitcpio.conf

echo "==> initcpio: Running mkinitcpio -P"
mkinitcpio -P

echo "==> initcpio: Complete"
