# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
dontChroot: true
timeout: 300
script:
  - "udevadm trigger"
  - "udevadm settle"
  - "arch-chroot \"${ROOT}\" bash -c 'if [ -d /sys/firmware/efi ]; then /usr/bin/grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=theonix --force --no-nvram; mkdir -p /boot/efi/EFI/BOOT; cp /boot/efi/EFI/theonix/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI; echo \"\\EFI\\BOOT\\BOOTX64.EFI\" > /boot/efi/startup.nsh; else /usr/bin/grub-install --target=i386-pc --force /dev/sda; fi'"
  - "arch-chroot \"${ROOT}\" /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg"
