# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
dontChroot: true
timeout: 300
script:
  - command: "arch-chroot ${ROOT} /usr/bin/grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=theonix --force --no-nvram"
  - command: "arch-chroot ${ROOT} mkdir -p /boot/efi/EFI/BOOT"
  - command: "arch-chroot ${ROOT} cp /boot/efi/EFI/theonix/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI"
  - command: "arch-chroot ${ROOT} /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg"
