# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
timeout: 300
script:
  - "/usr/bin/grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=theonix --force"
  - "mkdir -p /boot/efi/EFI/BOOT"
  - "cp /boot/efi/EFI/theonix/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI"
  - "bash -c 'echo \"\\EFI\\BOOT\\BOOTX64.EFI\" > /boot/efi/startup.nsh'"
  - "/usr/bin/grub-mkconfig -o /boot/grub/grub.cfg"
