# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the theonix-postinstall module.
---
# This custom module runs system services configuration and setup wizard marking.
