# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Unpackfs module configuration for Theonix OS.
# Extracts the live SquashFS image to the target partition.
---
unpack:
    - source: "/run/archiso/airootfs"
      sourcefs: "squashfs"
      destination: ""
