# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Users module configuration for Theonix OS.
---
defaultGroups:
    - name: users
      must_exist: false
      system: true
    - name: wheel
      must_exist: false
      system: true
    - name: lp
      must_exist: false
      system: true
    - name: video
      must_exist: false
      system: true
    - name: network
      must_exist: false
      system: true
    - name: storage
      must_exist: false
      system: true
    - name: audio
      must_exist: false
      system: true

autologinGroup: autologin

doAutologin: false

sudoersGroup: wheel

setRootPassword: true

doReusePassword: true

passwordRequirements:
    minLength: 1
    maxLength: -1

allowWeakPasswords: true

setHostname: EtcFile

writeHostsFile: true
